### ISSUE TITLE
Failed at Etcd Operator step - 

### ISSUE THREAD

**Issue by nmpvinh** [free5gmano/kube5gnfvo#9]
Hi @tw0927041027 ,

I follow the procedure and fail at Etcd Operator step. Could you please help to fix?
```
ubuntu@ubuntu-KVM:~/kube5gnfvo/example/etcd-cluster$ kubectl apply -f ./
deployment.extensions/etcd-operator created
deployment.apps/etcd-ui created
service/etcd-ui created
service/expose-dual-network-nic-etcd-cluster created
error: unable to recognize "example-etcd-cluster.yaml": no matches for kind "EtcdCluster" in version "etcd.database.coreos.com/v1beta2"
```
Here is the content of the file, seems the failure related to  apiVersion.
```
ubuntu@ubuntu-KVM:~/kube5gnfvo/example/etcd-cluster$ cat example-etcd-cluster.yaml
apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: "dual-network-nic-etcd-cluster"
  ## Adding this annotation make this cluster managed by clusterwide operators
  ## namespaced operators ignore it
  # annotations:
  #   etcd.database.coreos.com/scope: clusterwide
spec:
  size: 1
  version: "3.2.13"
ubuntu@ubuntu-KVM:~/kube5gnfvo/example/etcd-cluster$ 
```
Appreciated if you could provide some help to pass this step.
Thanks.
